services:
  db:
    image: postgres:14
    container_name: lovely-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=lovelycmd
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
